all:
	find . -type f -name '*.ps' -delete; \
	find . -type f -name '*.pyc' -delete; \
	find . -type f -name '*.out' -delete; \
	./src/myparser.py --help

clean:
	find . -type f -name '*.ps' -delete; \
	find . -type f -name '*.pyc' -delete; \
	find . -type f -name '*.out' -delete;
